language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
script: "npm run-script coverage"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
